FROM siro_resume-backend-main:latest

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

RUN mkdir -p /app/storage /app/output /app/hybrid_jobs /app/lowcost_jobs

EXPOSE 8000
EXPOSE 8007
EXPOSE 8008

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
